"use server";

import { signIn } from "@/auth";
import { AuthError } from "next-auth";
import { LoginFormType } from "../ui/login-form";
import { RegisterFormType } from "../ui/register-form";
import axios from "@/app/lib/axios";
import { ROUTES } from "@/constants/routes";
import { AxiosError } from "axios";
import { cookies } from "next/headers";

export async function authenticate(data: LoginFormType) {
  try {
    /**
     * Calls the signIn method generated by Next-Auth
     */
    const result = await axios.post(ROUTES.AUTH.LOGIN, data);

    cookies().set({
      name: "next_jwt",
      value: result.data.data.token,
      httpOnly: true,
    });

    return result.data.data.token;
  } catch (error) {
    /**
     * Login failed
     */
    if (error instanceof AxiosError) {
      throw new Error(error.response?.data.message);
    }
  }
}

export async function register(data: RegisterFormType) {
  try {
    /**
     * Register the new user.
     */
    const result = await axios.post(ROUTES.AUTH.REGISTER, data);

    /**
     * Calls the signIn method generated by Next-Auth
     */
    cookies().set({
      name: "next_jwt",
      value: result.data.data.token,
      httpOnly: true,
    });

    return result.data.data.token;
  } catch (error) {
    /**
     * Login failed
     */
    if (error instanceof AuthError) {
      switch (error.type) {
        case "CredentialsSignin":
          throw new Error("Invalid credentials");
        default:
          throw new Error("Something went wrong");
      }
    } else if (error instanceof AxiosError) {
      throw new Error(error.response?.data?.message);
    }

    throw error;
  }
}

export async function logout() {
  cookies().delete("next_jwt");
}

export async function getNewReleases() {
  try {
    const result = await axios.get("albums/new-releases");
    return result.data.albums;
  } catch (error) {
    if (error instanceof AxiosError) {
      throw new Error(error.response?.data.message);
    }
  }
}
